// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Models;

public partial class Level
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }
    
    [Required]
    [Column("description")]
    [StringLength(1000)]
    [Unicode(false)]
    public string Description { get; set; }
    
    [InverseProperty("Level")]
    public virtual ICollection<User> User { get; set; } = new List<User>();
}