// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Models;

public partial class Post
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("threadID")]
    public int ThreadId { get; set; }

    [Column("replyToPostID")]
    public int? ReplyToPostId { get; set; }

    [Column("userID")]
    public int UserId { get; set; }

    [Column("isOriginalPost")]
    public bool IsOriginalPost { get; set; }

    [Required]
    [Column("title")]
    [StringLength(300)]
    [Unicode(false)]
    public string Title { get; set; }

    [Required]
    [Column("text")]
    [Unicode(false)]
    public string Text { get; set; }

    [Column("createdAt")]
    public DateTimeOffset CreatedAt { get; set; }

    [Required]
    [Column("authorIpAdress")]
    [StringLength(100)]
    [Unicode(false)]
    public string AuthorIpAdress { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<Image> Image { get; set; } = new List<Image>();

    [InverseProperty("ReplyToPost")]
    public virtual ICollection<Post> InverseReplyToPost { get; set; } = new List<Post>();

    [ForeignKey("ReplyToPostId")]
    [InverseProperty("InverseReplyToPost")]
    public virtual Post ReplyToPost { get; set; }

    [ForeignKey("ThreadId")]
    [InverseProperty("Post")]
    public virtual Thread Thread { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Post")]
    public virtual User User { get; set; }
}