// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Models;

public partial class Rating
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("threadID")]
    public int ThreadId { get; set; }

    [Column("userID")]
    public int UserId { get; set; }

    [Column("isPositive")]
    public bool IsPositive { get; set; }

    [ForeignKey("ThreadId")]
    [InverseProperty("Rating")]
    public virtual Thread Thread { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Rating")]
    public virtual User User { get; set; }
}