// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Models;

public partial class Theme
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("description")]
    [Unicode(false)]
    public string Description { get; set; }

    [InverseProperty("Theme")]
    public virtual Image Image { get; set; }

    [InverseProperty("Theme")]
    public virtual ICollection<Thread> Thread { get; set; } = new List<Thread>();
}